root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gallery_index
        permanent: true

frontend:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin/app

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /admin/cart

gallery:
    resource: "@GalleryBundle/Controller/"
    type:     annotation
    prefix:   /admin/gallery

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"